MAP_WIDTH = 30
MAP_HEIGHT = 20

BASE_TICK_MS = 100
FOOD_SCORE = 10

P1_INIT_POS = [(5, MAP_HEIGHT // 2), (4, MAP_HEIGHT // 2), (3, MAP_HEIGHT // 2)]
P2_INIT_POS = [(MAP_WIDTH - 6, MAP_HEIGHT // 2), (MAP_WIDTH - 5, MAP_HEIGHT // 2), (MAP_WIDTH - 4, MAP_HEIGHT // 2)]

P1_INIT_DIR = (1, 0)
P2_INIT_DIR = (-1, 0)

BOOST_ENABLED = True
BOOST_DURATION_SEC = 5
BOOST_SPEED_MULTIPLIER = 2
BOOST_SPAWN_INTERVAL_SEC = 15
BOOST_SPAWN_CHANCE = 0.3

BOOST_CHAR = '*'
FOOD_CHAR = '*'
BORDER_CHAR = '#'
P1_HEAD_CHAR = 'O'
P1_BODY_CHAR = 'o'
P2_HEAD_CHAR = 'X'
P2_BODY_CHAR = 'x'

COLOR_P1_HEAD = 1
COLOR_P1_BODY = 2
COLOR_P2_HEAD = 3
COLOR_P2_BODY = 4
COLOR_FOOD = 5
COLOR_BOOST = 6
COLOR_BORDER = 7
